### ISSUE TITLE
What can be inproved

### ISSUE THREAD

**Issue by sabatesduran** [hackoor83/RandomLeaderPicker#1]
- [x] Right now you are creating multiple events and you could create 1 event that executes 2 functions.
```js
document.getElementById('leaderPicker').addEventListener('click', () => {
  leaderPicker();
  reviewersList();
});
```

- [x] As you said in you slack message you have repetitions, try to clone the original array and use the new array for the `forEach`, every time you iterate througth student delete the element that you just used for the table.

- [x] Doing the second task you can still have a problem, someone could have himself as reviewer.

**Comment by hackoor83** [comment]
Thanks @sabatesduran , I have done some modifications and I believe that improved the app. I would love to hear your opinion on this new version. I have renamed the files for the new version by adding '_V1' as a suffix for each file name.
